project:
  type: website
  output-dir: docs

website:
  title: "Cyrus Navasca"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: experiences.qmd
        text: Experiences
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: 
      light: yeti
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

